'''
1º FUNÇÃO: VERIFICA SE UMA PALAVRA ESTÁ PRESENTE NO VETOR CASO ENCONTRE A PALAVRA, RETORNA O ÍNDICE, SENÃO RETORNA -1
2º FUNÇÃO: COPIA DO INÍCIO DO VETOR TODAS AS PALAVRAS UMA POSIÇÃO A DIREITA
'''
